name: Ansible

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      ANSIBLE_HOST_KEY_CHECKING: False

    steps:
      # Git Clone/Pull
      - uses: actions/checkout@v3

      - name: Generate Key
        run: |
          echo "${{ secrets.ANSIBLE_SSH_KEY }}" > ansible_key
          chmod 400 ansible_key

      - name: Test Inventory
        uses: maurete/ansible-action@main
        with:
          playbook: main.yml
